interface Config {
    name: string,
    zoom: number,
    x: number,
    y: number,
    fixes: boolean,
    locs: boolean,
    airportNames: boolean,
    ctr: boolean,
    airport?: string
}
const configs: Config[] = [
    {
        name: "IRFD_CTR",
        zoom: 3,
        x: 100,
        y: -180,
        fixes: true,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "IRFD_TWR",
        zoom: 5,
        x: 100,
        y: -180,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
    },
    {
        name: "IMLR_TWR",
        zoom: 7,
        x: 108.5,
        y: -181,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
        airport: "IRFD"
    },
    {
        name: "IRFD_APP",
        zoom: 4,
        x: 100,
        y: -180,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: false,
    },
    {
        name: "IRFD_GND",
        zoom: 7,
        x: 100,
        y: -180,
        fixes: false,
        locs: false,
        airportNames: false,
        ctr: false,
    },
    {
        name: "IPPH_CTR",
        zoom: 3,
        x: 180.5,
        y: -71,
        fixes: true,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "IPPH_GND",
        zoom: 7,
        x: 181.25,
        y: -73,
        fixes: false,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "IPPH_APP",
        zoom: 5,
        x: 187.5,
        y: -80.5,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
    },
    {
        name: "IGRV_CTR",
        zoom: 3,
        x: 19,
        y: -120,
        fixes: true,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "IGRV_TWR",
        zoom: 5,
        x: 19.4,
        y: -119.7,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
    },
    {
        name: "IGRV_APP",
        zoom: 4,
        x: 19.4,
        y: -122.7,
        fixes: true,
        locs: true,
        airportNames: true,
        ctr: false,
    },
    {
        name: "IGRV_GND",
        zoom: 7,
        x: 19.4,
        y: -122.7,
        fixes: false,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "ITKO_CTR",
        zoom: 3,
        x: 100,
        y: -40,
        fixes: true,
        locs: true,
        airportNames: false,
        ctr: false,
    },
    {
        name: "ITKO_TWR",
        zoom: 5,
        x: 110,
        y: -40,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
    },
    {
        name: "IDCS_TWR",
        zoom: 7,
        x: 117,
        y: -9,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: true,
        airport: "ITKO"
    },
    {
        name: "ITKO_APP",
        zoom: 4,
        x: 100,
        y: -40,
        fixes: false,
        locs: true,
        airportNames: true,
        ctr: false,
    },
    {
        name: "ITKO_1_GND",
        zoom: 7,
        x: 110,
        y: -41,
        fixes: false,
        locs: false,
        airportNames: false,
        ctr: false,
    },
    {
        name: "ITKO_2_GND",
        zoom: 7,
        x: 115,
        y: -44,
        fixes: false,
        locs: false,
        airportNames: false,
        ctr: false,
    },
]

export { configs, type Config }

